#!/usr/bin/env python3
"""Regenerate files.txt -- the list the installer downloads.

Run this whenever you add, rename or delete a shipped file:

    python tools/make_manifest.py
"""
import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHIPPED_ROOTS = ("aurora",)
SHIPPED_FILES = ("startup.lua",)
SKIP_DIRS = {".git", "__pycache__", "var"}

HEADER = """\
# Aurora OS file manifest -- every file the installer fetches.
# Generated by tools/make_manifest.py; do not edit by hand.
"""


def collect():
    paths = list(SHIPPED_FILES)
    for top in SHIPPED_ROOTS:
        for base, dirs, names in os.walk(os.path.join(ROOT, top)):
            dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
            for name in sorted(names):
                rel = os.path.relpath(os.path.join(base, name), ROOT)
                paths.append(rel.replace("\\", "/"))
    return paths


def main():
    paths = collect()
    target = os.path.join(ROOT, "files.txt")
    with io.open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER)
        for path in paths:
            handle.write(path + "\n")
    print("wrote %s (%d files)" % (target, len(paths)))


if __name__ == "__main__":
    main()
